name: Update README Index

permissions:
  contents: write   # allow commits & pushes

on:
  push:
    paths:
      - 'problems/**/solution.py'
      - 'problems/**/solution.cpp'
      - 'problems/**/README.md'
      - 'scripts/generate_index.py'
      - '.github/workflows/update-readme.yml'
  workflow_dispatch:

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run generate_index.py
        run: python ./scripts/generate_index.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "docs(index): auto-update LeetCode problem table [skip ci]" || echo "No changes to commit"
          git push
